version: '3.5'
services:
  redis:
    image: redis:6.2.12
    container_name: redis
    hostname: redis
    restart: always
    command: redis-server --requirepass 123456 --appendonly yes
    ports:
      - "6379:6379"
    environment:
      TZ: "Asia/Shanghai"
    volumes:
      - ./data:/data
