server:
  port: 8081
spring:
  application:
    name: pong
resilience4j:
  ratelimiter:
    instances:
      pongRateLimiter:
        limit-for-period: 1
        limit-refresh-period: 1s
        timeout-duration: 0ms
rate-limit:
  pong:
    limit-for-period: 1
    limit-refresh-period: 1s
