server:
  port: 8080
spring:
  application:
    name: ping
  data:
    mongodb:
      uri: mongodb://root:123456@127.0.0.1:27017/logs_db
rate-limit:
  ping:
    lock-file: /Users/macbook/Downloads/tmp/rate_limiter.lock
    counter-file: /Users/macbook/Downloads/tmp/rate_counter.txt
    max-limit: 2
pong:
  url: http://127.0.0.1:8081/pong
