version: '3.5'
services:
  rmqnamesrv:
    image: apache/rocketmq:5.3.1
    container_name: rmqnamesrv
    ports:
      - "9876:9876"
    volumes:
      - ./namesrv/logs:/home/rocketmq/logs
    environment:
      TZ: "Asia/Shanghai"
    command: sh mqnamesrv
  rmqbroker:
    image: apache/rocketmq:5.3.1
    container_name: rmqbroker
    ports:
      - "10909:10909"
      - "10911:10911"
      - "10912:10912"
    volumes:
      - ./broker/logs:/home/rocketmq/logs
      - ./broker/store:/home/rocketmq/store
      - ./broker/conf/broker.conf:/home/rocketmq/rocketmq-5.3.1/conf/broker.conf
    environment:
      NAMESRV_ADDR: "rmqnamesrv:9876"
      TZ: "Asia/Shanghai"
    command: sh mqbroker -c /home/rocketmq/rocketmq-5.3.1/conf/broker.conf
    depends_on:
      - rmqnamesrv
  rmqconsole:
    image: apacherocketmq/rocketmq-dashboard:latest
    container_name: rmqconsole
    ports:
      - "19876:8080"
    environment:
      JAVA_OPTS: "-Drocketmq.namesrv.addr=rmqnamesrv:9876 -Dcom.rocketmq.sendMessageWithVIPChannel=false"
      TZ: "Asia/Shanghai"
    volumes:
      - ./rocketmq-console/logs:/root/logs
    depends_on:
      - rmqnamesrv
